GET /his/BasicInformationController/getAllDepartments HTTP/1.1
Host: localhost:9002

###

POST /his/BasicInformationController/addUser HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id":null,
  "username": "MyUsername",
  "password": "MyPassword",
  "realname": "MyRealName",
  "usertypeid": 2,
  "doctitleid": 1,
  "isscheduling": 1,
  "deptid": 3,
  "registerLevelId": 1,
  "delmark": 0,
  "idnumber": "3247875"
}


###
GET /his/BasicInformationController/getUsersBetweenScheduleDates?startDate=1&endDate=2 HTTP/1.1
Host: localhost:9002

###


GET /his/BasicInformationController/getPatientsBetweenScheduleDates?startDate=1&endDate=2 HTTP/1.1
Host: localhost:9002

###



POST /his/BasicInformationController/addDepartment HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "deptcode":"BYRK",
  "deptname":"变异人科",
  "depttypeid":2
}
###

GET /his/BasicInformationController/getDepartmentById?id=1 HTTP/1.1
Host: localhost:9002



###
POST /his/BasicInformationController/updateDepartment HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 139,
  "deptname": "变异人類科",
  "deptcategory": null,
  "depttypeid": 2,
  "deptcode": "BYRLK",
  "userList": null
}


###
GET /his/BasicInformationController/getAllConstantItems HTTP/1.1
Host: localhost:9002


###
POST /his/BasicInformationController/addConstantItem HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "constanttypeid": 1,
  "constantcode": "NKttttt",
  "constantname": "内科ttttttt"
}


###
POST /his/BasicInformationController/updateConstantItem HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 168,
  "constanttypeid": 1,
  "constantcode": "NKttttt",
  "constantname": "内科ttttttt9999999"
}


###
GET /his/BasicInformationController/getConstantItemById?id=11 HTTP/1.1
Host: localhost:9002


###
GET /his/BasicInformationController/getAllRegisterLevels HTTP/1.1
Host: localhost:9002



###
GET /his/BasicInformationController/getAllConstantTypes HTTP/1.1
Host: localhost:9002


###
POST /his/BasicInformationController/addConstantType HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "constanttypecode": "DeptCategory555555",
  "constanttypename": "科室分类555555"
}


###
GET /his/BasicInformationController/getConstantTypeById?id=1 HTTP/1.1
Host: localhost:9002


###
POST /his/BasicInformationController/updateConstantType HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 13,
  "constanttypecode": "DeptCategory",
  "constanttypename": "科室分类mmmmmmmmm"
}

###
GET /his/BasicInformationController/getRegisterLevelById?id=1 HTTP/1.1
Host: localhost:9002



###
POST /his/BasicInformationController/addRegisterLevel HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "registname": "超级号",
  "registfee": 333320.00
}


###
POST /his/BasicInformationController/updateRegisterLevel HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 4,
  "registname": "超级号",
  "registfee": 30020.00
}


###
GET /his/BasicInformationController/getAllSettleCategories HTTP/1.1
Host: localhost:9002


###
POST /his/BasicInformationController/addSettleCategory HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "settlename": "新农合"
}

###
GET /his/BasicInformationController/getSettleCategoryById?id=1 HTTP/1.1
Host: localhost:9002


###
POST /his/BasicInformationController/updateSettleCategory HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 1,
  "settlename": "醫保qqqqqqq"
}

###
GET /his/BasicInformationController/getAllExpenseClasses HTTP/1.1
Host: localhost:9002


###
POST /his/BasicInformationController/addExpenseClass HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "expname": "AZF",
  "expcode": "安葬费"
}


###
GET /his/BasicInformationController/getExpenseClassById?id=1 HTTP/1.1
Host: localhost:9002



###
POST /his/BasicInformationController/updateExpenseClass HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 23,
  "expname": "AZF",
  "expcode": "安葬费mmmmmmmmmm"
}




###
GET /his/BasicInformationController/getAllSchedulings HTTP/1.1
Host: localhost:9002


###
GET /his/BasicInformationController/getSchedulingById?id=1 HTTP/1.1
Host: localhost:9002

###
POST /his/BasicInformationController/updateScheduling HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 1,
  "scheddate": "2019-03-02",
  "deptid": 3,
  "userid": 1,
  "noon": 1,
  "registquota": 3,
  "state": 0,
  "user": null,
  "department": null
}


###
POST /his/BasicInformationController/addScheduling HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "userid": 100,
  "scheddate": "2020-12-02",
  "noon": 1,
  "registquota": 3
}

###
GET /his/BasicInformationController/getSchedulingsByConditions?userId=1&deptId=1&state=1&fromScheduleDate=2020-04-24&fromNoon=2&toScheduleDate=2020-04-25&toNoon=3 HTTP/1.1
Host: localhost:9002

