GET /his/BasicInformationController/getAllDepartments HTTP/1.1
Host: localhost:9002

###

POST /his/BasicInformationController/addUser HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id":null,
  "username": "MyUsername",
  "password": "MyPassword",
  "realname": "MyRealName",
  "usertypeid": 2,
  "doctitleid": 1,
  "isscheduling": 1,
  "deptid": 3,
  "registerLevelId": 1,
  "delmark": 0,
  "idnumber": "3247875"
}


###
GET /his/BasicInformationController/getUsersBetweenScheduleDates?startDate=1&endDate=2 HTTP/1.1
Host: localhost:9002

###


GET /his/BasicInformationController/getPatientsBetweenScheduleDates?startDate=1&endDate=2 HTTP/1.1
Host: localhost:9002

###



POST /his/BasicInformationController/addDepartment HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "deptcode":"BYRK",
  "deptname":"变异人科",
  "depttypeid":2
}
###

GET /his/BasicInformationController/getDepartmentById?id=1 HTTP/1.1
Host: localhost:9002



###
POST /his/BasicInformationController/updateDepartment HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 139,
  "deptname": "变异人類科",
  "deptcategory": null,
  "depttypeid": 2,
  "deptcode": "BYRLK",
  "userList": null
}




