GET /his/BasicInformationController/getAllDepartments HTTP/1.1
Host: localhost:9002

###

POST /his/BasicInformationController/addUser HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id":null,
  "username": "MyUsername",
  "password": "MyPassword",
  "realname": "MyRealName",
  "usertypeid": 2,
  "doctitleid": 1,
  "isscheduling": 1,
  "deptid": 3,
  "registerLevelId": 1,
  "delmark": 0,
  "idnumber": "3247875"
}


###
GET /his/BasicInformationController/getUsersBetweenScheduleDates?startDate=1&endDate=2 HTTP/1.1
Host: localhost:9002

###


GET /his/BasicInformationController/getPatientsBetweenScheduleDates?startDate=1&endDate=2 HTTP/1.1
Host: localhost:9002

###



POST /his/BasicInformationController/addDepartment HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "deptcode":"BYRK",
  "deptname":"变异人科",
  "depttypeid":2
}
###

GET /his/BasicInformationController/getDepartmentById?id=1 HTTP/1.1
Host: localhost:9002



###
POST /his/BasicInformationController/updateDepartment HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 139,
  "deptname": "变异人類科",
  "deptcategory": null,
  "depttypeid": 2,
  "deptcode": "BYRLK",
  "userList": null
}


###
GET /his/BasicInformationController/getAllConstantItems HTTP/1.1
Host: localhost:9002


###
POST /his/BasicInformationController/addConstantItem HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "constanttypeid": 1,
  "constantcode": "NKttttt",
  "constantname": "内科ttttttt"
}


###
POST /his/BasicInformationController/updateConstantItem HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 168,
  "constanttypeid": 1,
  "constantcode": "NKttttt",
  "constantname": "内科ttttttt9999999"
}


###
GET /his/BasicInformationController/getConstantItemById?id=11 HTTP/1.1
Host: localhost:9002


###
GET /his/BasicInformationController/getAllRegisterLevels HTTP/1.1
Host: localhost:9002



###
GET /his/BasicInformationController/getAllConstantTypes HTTP/1.1
Host: localhost:9002


###
POST /his/BasicInformationController/addConstantType HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "constanttypecode": "DeptCategory555555",
  "constanttypename": "科室分类555555"
}


###
GET /his/BasicInformationController/getConstantTypeById?id=1 HTTP/1.1
Host: localhost:9002


###
POST /his/BasicInformationController/updateConstantType HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 13,
  "constanttypecode": "DeptCategory",
  "constanttypename": "科室分类mmmmmmmmm"
}

###
GET /his/BasicInformationController/getRegisterLevelById?id=1 HTTP/1.1
Host: localhost:9002



###
POST /his/BasicInformationController/addRegisterLevel HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "registname": "超级号",
  "registfee": 333320.00
}


###
POST /his/BasicInformationController/updateRegisterLevel HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 4,
  "registname": "超级号",
  "registfee": 30020.00
}


###
GET /his/BasicInformationController/getAllSettleCategories HTTP/1.1
Host: localhost:9002


###
POST /his/BasicInformationController/addSettleCategory HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "settlename": "新农合"
}

###
GET /his/BasicInformationController/getSettleCategoryById?id=1 HTTP/1.1
Host: localhost:9002


###
POST /his/BasicInformationController/updateSettleCategory HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 1,
  "settlename": "醫保qqqqqqq"
}

###
GET /his/BasicInformationController/getAllExpenseClasses HTTP/1.1
Host: localhost:9002


###
POST /his/BasicInformationController/addExpenseClass HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "expname": "AZF",
  "expcode": "安葬费"
}


###
GET /his/BasicInformationController/getExpenseClassById?id=1 HTTP/1.1
Host: localhost:9002



###
POST /his/BasicInformationController/updateExpenseClass HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 23,
  "expname": "AZF",
  "expcode": "安葬费mmmmmmmmmm"
}




###
GET /his/BasicInformationController/getAllSchedulings HTTP/1.1
Host: localhost:9002


###
GET /his/BasicInformationController/getSchedulingById?id=1 HTTP/1.1
Host: localhost:9002

###
POST /his/BasicInformationController/updateScheduling HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 1,
  "scheddate": "2019-03-02",
  "deptid": 3,
  "userid": 1,
  "noon": 1,
  "registquota": 3,
  "state": 0,
  "user": null,
  "department": null
}


###
POST /his/BasicInformationController/addScheduling HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "userid": 100,
  "scheddate": "2020-12-02",
  "noon": 1,
  "registquota": 3
}

###
GET /his/BasicInformationController/getSchedulingsByConditions?userId=100&deptId=1&state=3&fromScheduleDate=2020-04-24&fromNoon=2&toScheduleDate=2020-12-25&toNoon=3&registerLevelId=100 HTTP/1.1
Host: localhost:9002



###
GET /his/BasicInformationController/getAllFmedItems HTTP/1.1
Host: localhost:9002


###
GET /his/BasicInformationController/getFmedItemById?id=2 HTTP/1.1
Host: localhost:9002


###
POST /his/BasicInformationController/addFmedItem HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "itemname": "中抢救",
  "format": "日",
  "price": 150.00,
  "expclassid": 16,
  "deptid": 133,
  "itemcode": "120200002"
}

###
POST /his/BasicInformationController/updateFmedItem HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 59,
  "itemname": "中抢救233333333",
  "format": "日",
  "price": 150.00,
  "expclassid": 16,
  "deptid": 133,
  "itemcode": "120200002"
}

###
POST /his/BasicInformationController/addDiagnosis HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "medicalid":1,
  "diseaseid":1
}

###
POST /his/BasicInformationController/updateDiagnosis HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 5,
  "medicalid":1,
  "diseaseid":2
}

###
GET /his/BasicInformationController/getAllDiagnoses HTTP/1.1
Host: localhost:9002


###
GET /his/BasicInformationController/getDiagnosisById?id=2 HTTP/1.1
Host: localhost:9002


###
GET /his/BasicInformationController/getDrugById?id=2 HTTP/1.1
Host: localhost:9002


###
GET /his/BasicInformationController/getAllDrugs HTTP/1.1
Host: localhost:9002


###
POST /his/BasicInformationController/addDrug HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "drugsName": "氟康唑氯化钠注射液(大扶康)23333333",
  "drugsFormat": "200mg×100ml/瓶",
  "drugsUnit": "瓶",
  "manufacturer": "辉瑞制药有限公司",
  "drugsDosage": "110",
  "drugsType": "101",
  "drugsPrice": 7.01,
  "mnemonicCode": "FKZLHNZSY(DFK)",
  "creationDate": "2019-02-28T16:00:00.000+0000",
  "lastUpdateDate": "2019-02-28T16:00:00.000+0000"
}

###
POST /his/BasicInformationController/updateDrug HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 101,
  "drugsName": "氟康唑氯化钠注射液(大扶康)awsl",
  "drugsFormat": "200mg×100ml/瓶",
  "drugsUnit": "瓶",
  "manufacturer": "辉瑞制药有限公司",
  "drugsDosage": "110",
  "drugsType": "101",
  "drugsPrice": 7.01,
  "mnemonicCode": "FKZLHNZSY(DFK)",
  "creationDate": "2019-02-28T16:00:00.000+0000",
  "lastUpdateDate": "2019-02-28T16:00:00.000+0000"
}