POST /his/DoctorController/admit?registrationId=1 HTTP/1.1
Host: localhost:9002

###


POST /his/DoctorController/admit?registrationId=100 HTTP/1.1
Host: localhost:9002




###

POST /his/DoctorController/addCheckApply HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "medicalId":1
}

###
GET /his/DoctorController/getCheckApplyById?id=1 HTTP/1.1
Host: localhost:9002

###

POST /his/DoctorController/updateCheckApply HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
    "id": 1,
    "medicalId": null,
    "creationTime": null,
    "totalSum": null,
    "objective": "I don't know....",
    "userId": null,
    "state": null,
    "invoiceNumber": null,
    "checkDetailedList": null
}



###

POST /his/DoctorController/updateMedicalRecord HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 1,
  "registerId": 2,
  "medicalReadme": "sdfsdfsdfsdf",
  "medicalPresent": null,
  "presentTreat": null,
  "medicalHistory": null,
  "medicalAllergy": null,
  "medicalPhysique": null,
  "medicalDiagnosis": null,
  "medicalHandling": null,
  "caseState": 2,
  "diagnosisList": null
}

###
POST /his/DoctorController/addPrescription HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "prescriptionName":"含笑半步癲"
}

###


GET /his/DoctorController/getPrescriptionById?id=1 HTTP/1.1
Host: localhost:9002

###
POST /his/DoctorController/updatePrescription HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
    "id": 1,
    "medicalId": 1,
    "userId": null,
    "prescriptionName": "葵花寶典",
    "prescriptionState": null,
    "prescriptionTime": null,
    "invoiceId": null,
    "prescriptionDetailedList": null
}

###
POST /his/DoctorController/addCheckDetailed HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "checkappid": 1
}
###

GET /his/DoctorController/getCheckDetailedById?id=1 HTTP/1.1
Host: localhost:9002



###
POST /his/DoctorController/updateCheckDetailed HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 1,
  "checkappid": 1,
  "checkprojid": 1,
  "deptid": 3,
  "position": "1",
  "state": 1,
  "price": 1.00,
  "identification": 1,
  "inspecttime": 111111,
  "result": "133333333333333333333333",
  "resulttime": 1,
  "operatorid": 1,
  "entryclerkid": 1
}

###
POST /his/DoctorController/addPrescriptionDetailed HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
}

###
GET /his/DoctorController/getPrescriptionDetailedById?id=1 HTTP/1.1
Host: localhost:9002



POST /his/DoctorController/updatePrescriptionDetailed HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
    "id": 1,
    "prescriptionid": 1,
    "drugsid": 1,
    "useage": "1",
    "dosage": "1",
    "frequency": "10000000",
    "price": 1.00,
    "quantity": 1,
    "drugs": null
}


###
GET /his/DoctorController/getCheckAppliesByConditions?userId=3&state=1 HTTP/1.1
Host: localhost:9002


###
GET /his/DoctorController/getPrescriptionsByConditions?userId=1&prescriptionState=1 HTTP/1.1
Host: localhost:9002


###
GET /his/DoctorController/getMedicalRecordByCaseNumber?caseNumber=3 HTTP/1.1
Host: localhost:9002


###
POST /his/DoctorController/confirmCheckApply?checkApplyId=200 HTTP/1.1
Host: localhost:9002


###
GET /his/DoctorController/getMedicalRecordsByConditions?userId=104&patientId=1&registrationId=1&caseState=2 HTTP/1.1
Host: localhost:9002

###
POST /his/DoctorController/finishDiagnosis?medicalRecordId=1 HTTP/1.1
Host: localhost:9002


###
POST /his/DoctorController/confirmPrescription?prescriptionId=1 HTTP/1.1
Host: localhost:9002

###




