POST /his/RegistrationController/addRegistration HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "realname": "Nelson",
  "gender": 1,
  "patientid": 100,
  "registerid": 101,
  "isbook": 0,
  "settleid": 100,
  "idnumber": "7989688077809873",
  "scheduleId":1
}

###

POST /his/RegistrationController/addInvoice HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "userid":1
}





###
GET /his/RegistrationController/getRegistrationById?id=1 HTTP/1.1
Host: localhost:9002


###
GET /his/RegistrationController/getInvoiceById?id=1 HTTP/1.1
Host: localhost:9002






###

POST /his/RegistrationController/updateRegistration HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 103,
  "realname": "Nelson",
  "gender": 1,
  "idnumber": "7989688077809873",
  "birthdate": null,
  "age": 30,
  "homeaddress": null,
  "medicalRecordId": null,
  "visitdate": "2020-06-18",
  "noon": 1,
  "deptid": 1,
  "userid": 100,
  "registid": 100,
  "settleid": 100,
  "isbook": 0,
  "registertime": 1587837243219,
  "registerid": 101,
  "visitstate": 0,
  "patientid": 100,
  "patientCostsList": null
}

###
POST /his/RegistrationController/updateInvoice HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
"id": 1,
"invoicenum": null,
"money": null,
"state": null,
"creationtime": null,
"userid": 2,
"dailystate": null,
"patientCostsList": null
}


###
POST /his/RegistrationController/addPatientCosts HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{

}

###
GET /his/RegistrationController/getPatientCostsById?id=1 HTTP/1.1
Host: localhost:9002


###
POST /his/RegistrationController/updatePatientCosts HTTP/1.1
Host: localhost:9002
Content-Type: application/json

{
  "id": 1,
  "invoiceid": null,
  "registerid": null,
  "name": "lllllllllllllllll",
  "price": null,
  "deptid": null,
  "state": null
}


###
GET /his/RegistrationController/getRegistrationsByConditions?userId=100&departmentId=1&visitState=0&fromVisitDate=2020-04-24&fromNoon=1&toVisitDate=2020-12-25&toNoon=1&registrationTypeId=100&needBook=0&patientId=100&settlementTypeId=100&registrarId=101&scheduleId=1 HTTP/1.1
Host: localhost:9002







###


